language: cpp
compiler:
  - gcc
#  - clang
# Make sure CMake is installed
install:
 - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:boost-latest/ppa
 - sudo apt-get update >/dev/null
 - sudo apt-get -q install libbz2-dev libstxxl-dev libstxxl1 libxml2-dev libzip-dev lua5.1 liblua5.1-0-dev rubygems libtbb-dev
 - sudo apt-get -q install g++-4.8
 - sudo apt-get install libboost1.54-all-dev
 - sudo apt-get install libgdal-dev
 # luabind
 - curl https://gist.githubusercontent.com/DennisOSRM/f2eb7b948e6fe1ae319e/raw/install-luabind.sh | sudo bash
 # osmosis
 - curl -s https://gist.githubusercontent.com/DennisOSRM/803a64a9178ec375069f/raw/ | sudo bash
 # cmake
 - curl -s https://gist.githubusercontent.com/DennisOSRM/5fad9bee5c7f09fd7fc9/raw/ | sudo bash
before_script:
 - rvm use 1.9.3
 - gem install bundler
 - bundle install
 - mkdir build
 - cd build
 - cmake .. $CMAKEOPTIONS -DBUILD_TOOLS=1
script:
 - make
 - make tests
 - make benchmarks
 - ./algorithm-tests
 - ./datastructure-tests
 - cd ..
 - cucumber -p verify
after_script:
# - cd ..
# - cucumber -p verify
branches:
  only:
    - master
    - develop
cache:
- bundler
- apt
env:
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-4.8" OSRM_PORT=5000 OSRM_TIMEOUT=60
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-4.8" OSRM_PORT=5010 OSRM_TIMEOUT=60
 - CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER=g++-4.8" OSRM_PORT=5020 OSRM_TIMEOUT=60
notifications:
 slack: mapbox:4A6euphDwfxAQnhLurXbu6A1
 irc:
  channels:
    - irc.oftc.net#osrm
  on_success: change
  on_failure: always
  use_notice: true
  skip_join: false

  recipients:
    - patrick@mapbox.com
  email:
    on_success: change
    on_failure: always
